<form class="form-login" action="" method='POST'>
	<div class="errorHandler alert alert-danger <?php if($this->feedback == '') echo 'no-display';?> ">
		<i class="icon-remove-sign"></i> 
		<?php 
			if ($this->feedback != "" || $this->form->isErrors()) {
         		echo $this->feedback;
			}
      	?>		
	</div>
	<fieldset>
		<div class="form-group">
			<span class="input-icon"> <?php echo $this->form->userName; ?><i class="icon-user"></i>
			</span>
		</div>
		<div class="form-group form-actions">
			<span class="input-icon"> <?php echo $this->form->password; ?><i class="icon-lock"></i> 
			</span>
		</div>
		<div class="form-actions" style='display:block'>
			<!-- 
			<label for="remember" class="checkbox-inline"> <input type="checkbox" class="grey remember" id="remember" name="remember"> Keep me signed in
			</label>
			 -->
			<button type="submit" class="btn btn-bricky pull-right">
				Đăng nhập <i class="icon-circle-arrow-right"></i>
			</button>
		</div>
	</fieldset>
</form>
