<div class="col-sm-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="clip-users-2"></i> Top sản phẩm xem nhiều
			<div class="panel-tools">
				<a class="btn btn-xs btn-link panel-collapse collapses" href="#"> </a>
				<a class="btn btn-xs btn-link panel-close" href="#"> <i
					class="icon-remove"></i>
				</a>
			</div>
		</div>
		<div class="panel-body panel-scroll" style="height: 300px">
			<table class="table table-striped table-hover" id="sample-table-1">
				<thead>
					<tr>
						<th class="center" width="80px">Hình ảnh</th>
						<th width="250px">Tên sản phẩm</th>
						<th class="hidden-xs" width="100px">Lượt xem</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php
					if ($this->productViews != NULL) {
						echo $this->partialLoop ( "_partials/{$this->controllerName}/list.phtml", $this->productViews );
					} else {
						echo '<tr class = "tblSkinRow"><td colspan = "15"><div class = "empty-data">Không tìm thấy dữ liệu!</div></td></tr>';
					}
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div class="col-sm-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="clip-users-2"></i> Top sản phẩm mới
			<div class="panel-tools">
				<a class="btn btn-xs btn-link panel-collapse collapses" href="#"> </a>
				<a class="btn btn-xs btn-link panel-close" href="#"> <i
					class="icon-remove"></i>
				</a>
			</div>
		</div>
		<div class="panel-body panel-scroll" style="height: 300px">
			<table class="table table-striped table-hover" id="sample-table-1">
				<thead>
					<tr>
						<th class="center" width="80px">Hình ảnh</th>
						<th width="250px">Tên sản phẩm</th>
						<th class="hidden-xs" width="100px">Lượt xem</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php
					if ($this->productViews != NULL) {
						echo $this->partialLoop ( "_partials/{$this->controllerName}/list.phtml", $this->productNew );
					} else {
						echo '<tr class = "tblSkinRow"><td colspan = "15"><div class = "empty-data">Không tìm thấy dữ liệu!</div></td></tr>';
					}
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
