<script>
	jQuery(document).ready(function() {				
		UITreeview.init();
		//UIModals.init();
	});
</script>

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title">Danh mục sản phẩm</h4>
</div>
<div class="modal-body">				
	<div id="tree">
		<ul id='treeData'>
		<?php  
			$this->cmsTreeView('', null, 0, $this->category, null, &$result);
			$result = preg_replace('/<ul[^>]*>(.*)<\/ul[^>]*>/i', '$1', $result);
			echo $result; 
		?>
		</ul>
	</div>				
</div>
<div class="modal-footer">	
	<button type="button" data-dismiss="modal" class="btn btn-primary">Ok</button>
</div>
	
