<div class='toolbar' align="right">
	<a class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => $this->controllerName, 'action' => 'add')) ?>"><i class="icon-plus"></i> Thêm</a>
	<a class="btn btn-bricky " href="delete-all" onclick="return confirm('Do you want to delete all ?')" ><i class="icon-trash"></i> Xóa tất cả</a>
	<!-- <a class="btn btn-green" href="/admin/product/trash"><i class="icon-trash"></i> Thùng rác</a> -->
</div>
<div class="row">
	<div class="col-md-12">		
		<div class="panel panel-default">	
			<div class="panel-heading">
				<i class="icon-external-link-sign"></i> Video
				<div class="panel-tools">
					<a class="btn btn-xs btn-link panel-collapse collapses" href="#"> </a> 
					<a class="btn btn-xs btn-link panel-expand" href="#"> <i class="icon-resize-full"></i>
					</a> <a class="btn btn-xs btn-link panel-close" href="#"> <i class="icon-remove"></i>
					</a>
				</div>
			</div>
			<div class="panel-body">
				
				<div class="row" style="float: left; width: 750px;margin-left:-5px">
					<form action="" method='POST'>
		             <div class="col-filter col-sm-2" >
		             	<?php
			                echo $this->formSelect('sl_status', $this->statusSelected, array('class' => 'form-control'), array("" => PLEASE_SELECT,
																											"1" => "Hoạt động",
																										"0" => "Không hoạt động"));
						?>
		             </div>
		             <div class="col-filter col-sm-2">
		             	<button type="submit" class="form-control btn btn-green" >Lọc <i class="icon-filter"></i></button>
	             	 </div>
	             	 <div class="col-filter col-sm-2">
		             	<button type="button" class="form-control btn btn-teal" onclick="location.href='/admin/support/show-all'">Reset <i class='clip-refresh'></i></button>
		             </div>
		             </form>
                 </div>
				<div class="row" style="float: right;">
				<form action="" Method="post">
					<div class="row-md-5" style="float: left; margin-right:10px">
						<div class="form-group" style="width: 195px;">
						<?php 
							$keyword = new Zend_Form_Element_Text('s_keyword');
							$keyword->addFilter('StringTrim')
									->setRequired(true)
									->addValidator('NotEmpty')
									->setAttrib('class', 'form-control')
									->setAttrib('placeholder', 'Nhập từ khóa cần tìm...')
									->setValue($this->keyword)
									->setDecorators(array('ViewHelper'));
							
							echo $keyword;
						?>
						</div>
					</div>
					<div class="row-md-1" style="float: left;margin-right:15px">
		             	<div class="form-group">
		             		<button type="submit" class="form-control btn btn-green">Tìm kiếm <i class="icon-search"></i></button>
		             	</div>
		             </div>
				</form>
				</div>
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>			
							<th width='30px'><input type="checkbox" id="check-all" class="checkall"></th>     
			                <th width='30px'>ID</th>     
			                <th width='150px' align="center">Họ tên</th>
			                <th width='150px' align="center">Họ tên (Tiếng anh)</th>
			                 <th width='150px'>Chức vụ</th>       
			                 <th width='150px'>Chức vụ (Tiếng anh)</th>       
			                 <th width='100px'>Điện thoại</th>       
			                 <th width='80px'>Skype</th>       
			                 <th width='80px'>Yahoo</th>       
			                <th width='50px'>Hiển thị</th>
			                <th width='80px'>Thao tác</th>
						</tr>
					</thead>
					<tbody>
						<?php
						if ($this->data != NULL) {
							echo $this->partialLoop ( "_partials/{$this->controllerName}/list.phtml", $this->data );
						} else {
							echo '<tr class = "tblSkinRow"><td colspan = "15"><div class = "empty-data">Không tìm thấy dữ liệu!</div></td></tr>';
						}
						?>
					</tbody>
				</table>
			</div>
		</div>
		<!-- end: BASIC TABLE PANEL -->
	</div>
</div>
<div align="center">
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    '_partials/pagination.phtml'); ?>
</div>
<script type="text/javascript" language="javascript">
    $(document).ready(function() {
    	updateStatusClick('.status', "ajax-edit-feature/", 'status');
    	updateStatusClick('.isDetailProduct', "ajax-edit-feature/", 'isDetailProduct');
    	updateElementChange('.txtWeight', "ajax-edit-feature/", 'weight');
    	removeElementClick('.delete-category', 'ajax-delete-feature/', 'REMOVE_ROW');
    	removeAllClick('.delete-all-category', 'ajax-delete/', 'REMOVE_ALL');          
    });
</script>