<?php echo $this->doctype()?>
<html>
<head>
  <?php echo $this->headTitle()?>
  <?php echo $this->headMeta()?>
  <?php echo $this->headLink() ?>	
  <?php echo $this->headScript() ?>	
</head>
<body class="login example2">
	<div class="main-login col-sm-4 col-sm-offset-4">
		<div class="logo">
			ĐĂNG NHẬP HỆ THỐNG
		</div>
		<div class="box-login">
			<h3></h3>
			
      		<?php echo $this->layout()->content;?>  
    	</div>
		<div class="copyright">2014 &copy; Facecom Viet Nam.</div>
	</div>
</body>
</html>
