<div class="row">
	<div class="col-sm-12">
		<!-- start: PAGE TITLE & BREADCRUMB -->
		<ol class="breadcrumb">
			<!--<li><i class="clip-grid-6"></i> <a href="#"> Tables </a></li>
			<li class="active">Data Table</li>
			<?php echo $this->navigation()->breadcrumbs()->render(); ?>
			<li class="search-box">
				<form class="sidebar-search">
					<div class="form-group">
						<input type="text" placeholder="Start Searching...">
						<button class="submit">
							<i class="clip-search-3"></i>
						</button>
					</div>
				</form>
			</li>-->
		</ol>
		<div class="page-header">
			<!-- <h1>
				Data Tables <small>dynamic tables samples</small>
			</h1> -->
		</div>
		<!-- end: PAGE TITLE & BREADCRUMB -->
	</div>
</div>