<?php
if (isset($this->popupMessage)) {
    echo $this->popupMessage;
}

$formImage = '<div class="fileupload fileupload-new" data-provides="fileupload">
					<input type="hidden" value="" name="">
					<div class="fileupload-new thumbnail no-image" style="width: 150px; height: 120px;">
						<div class="fileupload-image"><i class="clip-image"></i></div>
					</div>
					<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 150px; max-height: 120px; line-height: 10px;"></div>
					<div>
						<span class="btn btn-light-grey btn-file"><span class="fileupload-new"><i class="icon-picture"></i> Select image</span><span class="fileupload-exists"><i class="icon-picture"></i> Change</span>
							<input type="file" name="image"/>
						</span>
						<a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
							<i class="icon-remove"></i> Remove
						</a>
						<span style="color:red">Upload image size:  1030px x 385px</span>
					</div>
				</div>';

$arrInput = array(
    0 => array('label' => 'Tiêu đề : ', 'input' => $this->form->titleVi, 'requited' => 'YES'),
	1 => array('label' => 'Tiêu đề (Tiếng anh): ', 'input' => $this->form->titleEn, 'requited' => 'NO'),
	2 => array('label' => 'Tóm tắt: ', 'input' => $this->form->introVi, 'requited' => 'NO'),
    3 => array('label' => 'Tóm tắt (Tiếng anh): ', 'input' => $this->form->introEn, 'requited' => 'NO'),
    4 => array('label' => 'Website: ', 'input' =>  $this->form->website, 'requited' => 'NO'),
	5 => array('label' => 'Thứ tự: ', 'input' => $this->form->weight, 'requited' => 'NO'),
	6 => array('label' => 'Hiển thị: ', 'input' => $this->form->status, 'requited' => 'NO'),
	//6 => array('label' => 'Type: ', 'input' => $categoryId, 'requited' => 'NO'),
	7 => array('label' => 'Hình ảnh: ', 'input' => $formImage, 'requited' => 'NO'),
	//6 => array('label' => 'image: ', 'input' => $this->form->image, 'requited' => 'NO'),
	
);
ksort($arrInput);
?>

<form role="form" class='form-horizontal' novalidate="novalidate" action='' method="post" enctype="multipart/form-data" onsubmit="return checkForm()">
	<div class="row">
		<div class="col-md-12">
			<!-- start: FORM VALIDATION 1 PANEL -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="icon-external-link-sign"></i>				
				</div>
				<div class="panel-body">
					<div class="tabbable panel-tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#panel_tab_example1">Thông tin chung</a>
							</li>					
						</ul>
									
						<div class="tab-content">
							<div class="col-md-12">
								<div id="alert-message"></div>							
					            <?php if (isset($this->error) && $this->error != '') { ?>
								<div class="errorHandler alert alert-danger">
									<i class="icon-remove-sign"></i> Message
									<ul>
				                        <?php
					                        foreach ($this->error as $item) {
					                            echo '<li>' . $item . '</li>';
					                        }
				                        ?>
				                    </ul>
								</div>
								<?php } ?>
								
								<div class="successHandler alert alert-success no-display">
									<i class="icon-ok"></i> Your form validation is successful!
								</div>
							</div>
							<div id="panel_tab_example1" class="tab-pane active">											
								<?php echo $this->partialLoop("_partials/row.phtml", $arrInput); ?>  														
							</div>
							<div id="panel_tab_example2" class="tab-pane">											
								<div class="row">	
									<div class="col-md-12" id='featureDetail'></div>
								</div>
								<div class="row">	
									<div class="col-md-12">
										<div class="form-group">
											<label class="col-sm-2 control-label"></label>	
											<div class="col-sm-9" id='image-attr'></div>											
										</div>
									</div>
								</div> 														
							</div>
							
						</div>
					</div>					
					
					<div class="row">
						<div class="col-md-12">
							<div><hr></div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-9">
							<p>Fields with <span class="symbol required"></span> are required</p>
						</div>
						<div class="col-md-3">
							<a data-style="expand-left" class="btn btn-teal ladda-button" href='<?php echo $this->url(array('module' => 'admin', 'controller' => $this->controllerName, 'action'=>'index')); ?>'>								
								<i class="icon-circle-arrow-left"></i><span class="ladda-label"> Cancel </span>
								<span class="ladda-spinner"></span>
							</a>
							<button type="submit" data-style="expand-right" name='btnSave' class="btn btn-teal ladda-button">
								<span class="ladda-label"> Save </span>
								<i class="icon-circle-arrow-right"></i>
								<span class="ladda-spinner"></span>
							</button>
						</div>
						
					</div>					
				</div>
			</div>
			<!-- end: FORM VALIDATION 1 PANEL -->
		</div>
	</div>
</form>

<script type="text/javascript">
	$(document).ready(function() {
		
	    $('#categoryId').change(function() {
	        var level = $(this + 'option:selected').attr('data-level');
	        if ($(this)[0].selectedIndex === 0) {
	            level = 0;
	        }
	        
	        $('#level').val(parseInt(level) + 1);
	    });
	});
    function checkForm() {
        var error = true;
        var stError = '';
        
        if ($('#title').val() === '') {
            stError += '<li>Title is not empty</li>';
            $('#title').addClass('required-error');
            error = false;
        } else {
            $('#title').removeClass('required-error');
        }
        
        if (!error) {
            $('.errorHandler').remove();
            $('#alert-message').html('<div class="errorHandler alert alert-danger"><button data-dismiss="alert" class="close" type="button">×</button><i class="icon-remove-sign"></i> Message</div>');
            $('.errorHandler').append('<ul>' + stError + '</ul>');
            $('#alert-message').fadeIn();
        }

        return error;
    }
</script>