<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <?php echo $this->headTitle();?>
        <?php echo $this->headMeta();?>
        <?php echo $this->headLink(); ?>	
        <?php echo $this->headScript();?>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-55126283-1', 'auto');
		  ga('send', 'pageview');

		</script>

</head>
<body>
	<div id="page">
		<div id="head">
			<img src="<?php echo TEMPLATE_DEFAULT_URL;?>/images/head.png" alt="" width="1029" height="144" />
			<div id="language">
				<span>
				  <a href="?l=vi"><img src="<?php echo TEMPLATE_DEFAULT_URL;?>/images/vn.png" alt="" width="25" height="17"></a>&nbsp;
				  <a href="?l=en"><img src="<?php echo TEMPLATE_DEFAULT_URL;?>/images/en.jpg" alt="" width="25" height="17"></a>&nbsp;
				  <a href="#"><img src="<?php echo TEMPLATE_DEFAULT_URL;?>/images/kr.png" alt="" width="25" height="17"></a>&nbsp;
				  <a href="#"><img src="<?php echo TEMPLATE_DEFAULT_URL;?>/images/jp.jpg" alt="" width="25" height="17"></a>
				</span>
			  </div>
		</div>
		<!-- #entete -->
		<div class="bg-navi">
			<?php 
				$menuTopBlock = new Default_Blocks_MenuTop();
				$menuTopBlock->menuTop();
			?>
		</div>
		<div id="slide">
			<?php 
				$slideShowHomeBlock = new Default_Blocks_SlideShowHome();
				$slideShowHomeBlock->slideShowHome();
			?>
			<!-- 
			<img src="images/slide/slide1.jpg" alt="" width="1030" height="385" />
			 -->
		</div>
		<div id="principale">

			<div id="colleft">
				<?php 
					$videoBlock = new Default_Blocks_Video();
					$videoBlock->video();
					
					$menuBlock = new Default_Blocks_Menu();
					$menuBlock->menu();
					
					$supportBlock = new Default_Blocks_Support();
					$supportBlock->support();
					
					$hitsBlock = new Default_Blocks_Hits();
					$hitsBlock->hits();
					
					/*$productHotBlock = new Default_Blocks_ProductHot();
					$productHotBlock->productHot();*/
				?>
				
			</div>
			<!-- #colonneGauche -->
			<div id="centre">

				<div id="contenu">
					 <?php echo $this->layout()->content;?>
				</div>
				<!-- #contenu -->
			</div>
			<!-- #centre -->

			<div class="clearb"></div>
		</div>
		<!-- #principale -->
		<div id="adresse">
			<?php 
				$footerBlock = new Default_Blocks_Footer();
				$footerBlock->footer();
			?>
		</div>
	</div>
		<!--
		<div class="language">
        <div class="box-social">
            
            <div class="fb-like" data-href="<?php echo BASE_URL;?>" data-layout="button_count" data-action="like" data-show-faces="true"></div>
        </div>
		-->
		
		<div class='socials language'>
			<div id="fb-root"></div>
            <script>
                (function(d, s, id){
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;
                    js.src = "//connect.facebook.net/en_EN/all.js#xfbml=1";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>
			<div class='box-social'>
			  <div class="fb-like" data-href="<?php echo BASE_URL;?>" data-layout="box_count" data-action="like" data-show-faces="true" data-send="true"></div>
			</div>
			<div class='box-social'>
			  <script type="text/javascript">
                window.___gcfg = {lang: "vi"};    
                (function(){
                    var po = document.createElement("script"); po.type = "text/javascript"; po.async = true;
                    po.src = "https://apis.google.com/js/plusone.js";
                    var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(po, s);
                })();
            </script>
            <div class="g-plusone" data-size="tall" data-href="https://plus.google.com/116128555720346215567/posts"></div>
			</div>
		</div>
		</div>
        
    </div>
<script>window.jQuery||document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"><\/script>')</script><script src="http://uhchat.net/admin/code.php?f=25a133"></script>
</body>
</html>