<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <?php echo $this->headTitle();?>
        <?php echo $this->headMeta();?>
        <?php echo $this->headLink(); ?>	
        <?php echo $this->headScript();?>
		
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-55126283-1', 'auto');
		  ga('send', 'pageview');

		</script>
</head>
<body>
<div id="page">
	<div id="head">
  <img src="images/head.png" alt="" width="1029" height="144" /></div>
	<!-- #entete -->
  <div class="bg-navi">
    <div class="navigationleft"><div class="navigationright">
    <div class="navigation">
    <ul>
    <li><a href="">TRANG CHỦ</a></li>
    <li><a href="">GIỚI THIỆU</a></li>
    <li><a href="">SẢN PHẨM</a></li>
    <li><a href="">DỰ ÁN</a></li>
    <li><a href="">TUYỂN DỤNG</a></li>
    <li><a href="">TIN TỨC</a></li>
    <li><a href="">LIÊN HỆ</a></li>
    </ul>
    </div>
    </div></div>
    </div>
   <div id="slide"><img src="images/slide/slide1.jpg" alt="" width="1030" height="385" /></div>
	<div id="principale">
   
		<div id="colleft">
		<div id="colleft-title1">VIDEO</div>	
		  <img src="images/video.jpg" alt="" width="233" height="169" />
        <div id="colleft-title2">DANH MỤC SẢN PHẨM</div> 
        <ul>
        <li class="bg-menu"><a href="#">Sơn expoxy nền xưởng</a></li>
         <li><a href="#">Sơn Epoxy sàn nhà giữ xe</a></li>
          <li class="bg-menu"><a href="#">Sơn Epoxy sàn nhà</a></li>
           <li><a href="#">Sơn Epoxy nền sân tennis</a></li>
          <li class="bg-menu"><a href="#">Sơn Epoxy sàn sân thể thao</a></li>
            <li><a href="#">Sơn Epoxy sàn sân thể thao</a></li>
        </ul> 
         <div id="colleft-title3">HỖ TRỢ TRỰC TUYẾN</div> 
         <p></p>
         <p></p>
         <p></p>
          <p></p>
         <p></p>
         <div id="colleft-title4">SỐ LƯỢNG TRUY CẬP</div> 
          <p></p>
         <p></p>
          <p></p>
         <p></p>
         <p></p>
          <div id="colleft-title5">SẢN PHẨM KHÁC</div> 
          <p></p>
         <p></p>
          <p></p>
         <p></p>
         <p></p>
          <!-- InstanceBeginEditable name="colonne_gauche" -->		
			<!-- InstanceEndEditable -->
		</div>
		<!-- #colonneGauche -->
		<div id="centre">
		
	  <div id="contenu">
				<!-- InstanceBeginEditable name="contenu" -->
               <div class="img-pro"><img src="images/image1.jpg" alt="" width="198" height="144" /></div>
               <p><strong>Sơn Epoxy nền xưởng</strong><br />
Hương pháp chúng tôi thi công sơn epoxy là sơn lăn và sơn tự phẳng. Tùy thuộc vào nhu cầu và việc sử dụng sàn hợp mục đích cũng như thẩm mỹ cho ngôi nhà, hay xưởng, kho… cho phù hợp. Để sơn sàn, sơn nền công thi son epoxy Hoàng Gia sẽ tiến hành khảo sát bề mặt, khâu này là rất quang trọng vì ảnh hưởng đến chất lượng cũng như độ bềnvững của sơn. Tiếp theo là đưa ra phương pháp thi công thích hợp cùng với lựa chọn </p>
<div class="clearb"><br /></div>
<div class="img-pro"><img src="images/image1.jpg" alt="" width="198" height="144" /></div>
               <p><strong>Sơn Epoxy nền xưởng</strong><br />
Hương pháp chúng tôi thi công sơn epoxy là sơn lăn và sơn tự phẳng. Tùy thuộc vào nhu cầu và việc sử dụng sàn hợp mục đích cũng như thẩm mỹ cho ngôi nhà, hay xưởng, kho… cho phù hợp. Để sơn sàn, sơn nền công thi son epoxy Hoàng Gia sẽ tiến hành khảo sát bề mặt, khâu này là rất quang trọng vì ảnh hưởng đến chất lượng cũng như độ bềnvững của sơn. Tiếp theo là đưa ra phương pháp thi công thích hợp cùng với lựa chọn </p>
<div class="clearb"><br /></div>
<div class="img-pro"><img src="images/image1.jpg" alt="" width="198" height="144" /></div>
               <p><strong>Sơn Epoxy nền xưởng</strong><br />
Hương pháp chúng tôi thi công sơn epoxy là sơn lăn và sơn tự phẳng. Tùy thuộc vào nhu cầu và việc sử dụng sàn hợp mục đích cũng như thẩm mỹ cho ngôi nhà, hay xưởng, kho… cho phù hợp. Để sơn sàn, sơn nền công thi son epoxy Hoàng Gia sẽ tiến hành khảo sát bề mặt, khâu này là rất quang trọng vì ảnh hưởng đến chất lượng cũng như độ bềnvững của sơn. Tiếp theo là đưa ra phương pháp thi công thích hợp cùng với lựa chọn </p>
<div class="clearb"><br /></div>
<div class="img-pro"><img src="images/image1.jpg" alt="" width="198" height="144" /></div>
               <p><strong>Sơn Epoxy nền xưởng</strong><br />
Hương pháp chúng tôi thi công sơn epoxy là sơn lăn và sơn tự phẳng. Tùy thuộc vào nhu cầu và việc sử dụng sàn hợp mục đích cũng như thẩm mỹ cho ngôi nhà, hay xưởng, kho… cho phù hợp. Để sơn sàn, sơn nền công thi son epoxy Hoàng Gia sẽ tiến hành khảo sát bề mặt, khâu này là rất quang trọng vì ảnh hưởng đến chất lượng cũng như độ bềnvững của sơn. Tiếp theo là đưa ra phương pháp thi công thích hợp cùng với lựa chọn </p>
<div class="clearb"><br /></div>

				<!-- InstanceEndEditable -->
			</div>
			<!-- #contenu -->
		</div>
		<!-- #centre -->
		
	  <div class="clearb"></div> 
	</div>
	<!-- #principale -->
	<div id="adresse">
	  <div id="menufoot">
	   <ul>
    <li><a href="">TRANG CHỦ</a></li>
    <li><a href="">GIỚI THIỆU</a></li>
    <li><a href="">SẢN PHẨM</a></li>
    <li><a href="">DỰ ÁN</a></li>
    <li><a href="">TUYỂN DỤNG</a></li>
    <li><a href="">TIN TỨC</a></li>
    <li><a href="">LIÊN HỆ</a></li>
    </ul>
		
		</div>
        <p>Thien than nho travel Số 9 Nguyễn thị minh khai, Phường 6, Quận 3, TP.HCM<br />
ĐT: (08) 38204571 - 38204572 - Fax: (08) 38204672 - Hotline: 0973366699 - Email: thien than nho.vn<br />
Website được thiết kế và xây dựng bởi Facecom việt nam</p>
		<!-- #liens_bas -->
	</div>
	<!-- #adresse -->
</div>
<!-- #page -->
<!-- InstanceBeginEditable name="scripts2" --><!-- InstanceEndEditable -->

</body>
</html>